[package]
name = "veilid-http-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
bytes.workspace = true
rmp-serde.workspace = true
veilid-http-core = { path = "../veilid-http-core" }
veilid-http-wire = { path = "../veilid-http-wire" }
http.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true
