[package]
name = "veilid-http-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true
veilid-http-core = { path = "../veilid-http-core" }
veilid-http-stream = { path = "../veilid-http-stream" }
veilid-http-wire = { path = "../veilid-http-wire" }

[lints]
workspace = true
