daemon:
  enabled: false
client_api:
  enabled: true
  listen_address: '127.0.0.1:5959'
  ipc_enabled: true
auto_attach: true
logging:
  system:
    enabled: false
    level: 'info'
  terminal:
    enabled: true
    level: 'info'
  file:
    enabled: false
    path: ''
    append: true
    level: 'info'
  api:
    enabled: true
    level: 'info'
  otlp:
    enabled: false
    level: 'trace'
    grpc_endpoint: 'localhost:4317'
  console:
    enabled: false
testing:
  subnode_index: 0
core:
  program_name: 'VeilidHttp Server'
  namespace: 'veilid-http-server'
  protected_store:
    allow_insecure_fallback: true
    always_use_insecure_storage: true
    directory: '/data/veilid/protected-store'
    delete: false
  table_store:
    directory: '/data/veilid/table-store'
    delete: false
  block_store:
    directory: '/data/veilid/block-store'
    delete: false
  network:
    protocol:
      udp:
        enabled: true
        socket_pool_size: 0
        listen_address: ':5150'
      tcp:
        connect: true
        listen: true
        max_connections: 256
        listen_address: ':5150'
      ws:
        connect: true
        listen: true
        max_connections: 256
        listen_address: ':5150'
        path: 'ws'
      wss:
        connect: true
        listen: false
        max_connections: 256
        listen_address: ':5150'
        path: 'ws'
