[package]
name = "veilid-http-veilid-remote"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
veilid-core = "=0.5.5"
veilid-remote-api = "=0.5.5"
veilid-http-transport = { path = "../veilid-http-transport" }

[lints]
workspace = true
