[package]
name = "veilid-http-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blake3.workspace = true
bytes.workspace = true
thiserror.workspace = true
veilid-http-wire = { path = "../veilid-http-wire" }
zstd.workspace = true

[lints]
workspace = true
